# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belle.Week'),
        ),
    ]
