# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='day',
            field=models.IntegerField(default=0),
        ),
    ]
